### ISSUE TITLE
Invalid length while reading varlength buffer.

### ISSUE THREAD

**Issue by cryptcoin-junkey** [monaco-ex/bitcore-lib#1]
With monacore-node.

```
insight-mona_1       | [2017-07-27T08:02:49.838Z] error: uncaught exception: { Invalid state: Invalid length while reading varlength buffer. Expected to read: 146 and read 99
insight-mona_1       | Error
insight-mona_1       |     at NodeError (/home/node/insight/node_modules/bitcore-lib/lib/errors/index.js:20:41)
insight-mona_1       |     at Object.checkState (/home/node/insight/node_modules/bitcore-lib/lib/util/preconditions.js:9:13)
insight-mona_1       |     at BufferReader.readVarLengthBuffer (/home/node/insight/node_modules/bitcore-lib/lib/encoding/bufferreader.js:141:5)
insight-mona_1       |     at Function.Input.fromBufferReader (/home/node/insight/node_modules/bitcore-lib/lib/transaction/input/input.js:95:28)
insight-mona_1       |     at Transaction.fromBufferReader (/home/node/insight/node_modules/bitcore-lib/lib/transaction/transaction.js:307:23)
insight-mona_1       |     at Function._fromBufferReader (/home/node/insight/node_modules/bitcore-lib/lib/block/block.js:92:42)
insight-mona_1       |     at Function.fromBufferReader (/home/node/insight/node_modules/bitcore-lib/lib/block/block.js:103:20)
insight-mona_1       |     at Function.fromBuffer (/home/node/insight/node_modules/bitcore-lib/lib/block/block.js:112:16)
insight-mona_1       |     at Function.fromString (/home/node/insight/node_modules/bitcore-lib/lib/block/block.js:121:16)
insight-mona_1       |     at /home/node/insight/node_modules/monacore-node/lib/services/bitcoind.js:1689:40
insight-mona_1       |   message: 'Invalid state: Invalid length while reading varlength buffer. Expected to read: 146 and read 99',
insight-mona_1       |   stack: 'Invalid state: Invalid length while reading varlength buffer. Expected to read: 146 and read 99\nError\n    at NodeError (/home/node/insight/node_modules/bitcore-lib/lib/errors/index.js:20:41)\n    at Object.checkState (/home/node/insight/node_modules/bitcore-lib/lib/util/preconditions.js:9:13)\n    at BufferReader.readVarLengthBuffer (/home/node/insight/node_modules/bitcore-lib/lib/encoding/bufferreader.js:141:5)\n    at Function.Input.fromBufferReader (/home/node/insight/node_modules/bitcore-lib/lib/transaction/input/input.js:95:28)\n    at Transaction.fromBufferReader (/home/node/insight/node_modules/bitcore-lib/lib/transaction/transaction.js:307:23)\n    at Function._fromBufferReader (/home/node/insight/node_modules/bitcore-lib/lib/block/block.js:92:42)\n    at Function.fromBufferReader (/home/node/insight/node_modules/bitcore-lib/lib/block/block.js:103:20)\n    at Function.fromBuffer (/home/node/insight/node_modules/bitcore-lib/lib/block/block.js:112:16)\n    at Function.fromString (/home/node/insight/node_modules/bitcore-lib/lib/block/block.js:121:16)\n    at /home/node/insight/node_modules/monacore-node/lib/services/bitcoind.js:1689:40' }
```

**Comment by cryptcoin-junkey** [comment]
I found out the similar log. https://gist.github.com/killerstorm/e64262ec01c55343f941bf73149a8f4c
But there is no information about the solution.

**Comment by cryptcoin-junkey** [comment]
The root cause is SegWit transaction support. It was already fixed.
